config/routes.rb
Rails.application.routes.draw do
  resources :coche_datos do
		collection do
			get :search
			get :ajax_search
			get :retrieve_searches
			get :buscar_autocomplete
			get :index_latest_autocomplete
			get :buscar_latest_autocomplete # fetches JSON data via GET request

			get :search_all_cars
			post :noCar_noOrigin_noYear_noMpg_noHorsepower 
			post :yesCar_noOrigin_noYear_noMpg_noHorsepower 
			post :noCar_noOrigin_noYear_noMpg_yesHorsepower
			post :noCar_noOrigin_noYear_yesMpg_noHorsepower
			post :noCar_noOrigin_noYear_yesMpg_yesHorsepower
			post :noCar_noOrigin_yesYear_noMpg_noHorsepower
			post :noCar_noOrigin_yesYear_noMpg_yesHorsepower
			post :noCar_noOrigin_yesYear_yesMpg_noHorsepower

			post :noCar_noOrigin_yesYear_yesMpg_yesHorsepower
			post :noCar_yesOrigin_noYear_noMpg_noHorsepower
			post :noCar_yesOrigin_noYear_noMpg_yesHorsepower
			post :noCar_yesOrigin_noYear_yesMpg_noHorsepower
			post :noCar_yesOrigin_noYear_yesMpg_yesHorsepower
			post :noCar_yesOrigin_yesYear_noMpg_noHorsepower
			post :noCar_yesOrigin_yesYear_noMpg_yesHorsepower
			post :noCar_yesOrigin_yesYear_yesMpg_noHorsepower
			post :noCar_yesOrigin_yesYear_yesMpg_yesHorsepower
			# post :yesCar_noOrigin_noYear_noMpg_noHorsepower
			post :yesCar_noOrigin_noYear_noMpg_yesHorsepower
			post :yesCar_noOrigin_noYear_yesMpg_noHorsepower
			post :yesCar_noOrigin_noYear_yesMpg_yesHorsepower
			post :yesCar_noOrigin_yesYear_noMpg_noHorsepower
			post :yesCar_noOrigin_yesYear_noMpg_yesHorsepower
			post :yesCar_noOrigin_yesYear_yesMpg_noHorsepower
			post :yesCar_noOrigin_yesYear_yesMpg_yesHorsepower
			post :yesCar_yesOrigin_noYear_noMpg_noHorsepower
			post :yesCar_yesOrigin_noYear_noMpg_yesHorsepower
			post :yesCar_yesOrigin_noYear_yesMpg_noHorsepower
			post :yesCar_yesOrigin_noYear_yesMpg_yesHorsepower
			post :yesCar_yesOrigin_yesYear_noMpg_noHorsepower
			post :yesCar_yesOrigin_yesYear_noMpg_yesHorsepower
			post :yesCar_yesOrigin_yesYear_yesMpg_noHorsepower
			post :yesCar_yesOrigin_yesYear_yesMpg_yesHorsepower
		end
	end

	# root 'coche_datos#index'
	# root 'statics#home'
	root 'coche_datos#index_autocomplete'
	# get 'coche_datos/buscar_autocomplete', to: 'coche_datos#buscar_autocomplete'

  resources :statics do
		collection do
			get :test
			get :get_data
			get :hide_data
			get :renovated_search
			post :retrieve_searches
			post :post_car_name
		end
	end

	post 'statics/execute_search', to: 'statics#execute_search'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
	# root 'statics#index'
end

app/models/static.rb
class Static < ApplicationRecord
end

app/controllers/statics_controller.rb
class StaticsController < ApplicationController
  before_action :set_static, only: %i[ show edit update destroy ]

	def home
	end

	def test
	end

	def get_data
		@test_data = "hello world!"
		respond_to do |format|
			format.js { render layout: false }
		end
	end

	def hide_data
		respond_to do |format|
			format.js { render layout: false }
		end
	end

	def renovated_search
		@rhs_coches = CocheDato.all.order(:car)
	end

	def retrieve_searches
		# @search_results_posts = CocheDato.suggestSearchCarName(params["carName"])
		@search_results_posts = CocheDato.suggestCarNameOrigin(params["carName"], params["originName"])
		puts "==========================="
		puts MultiJson.dump(CocheDato.mapping.to_hash, pretty: true)
		puts "==========================="
		respond_to do |format|
			format.js { render layout: false }
		end
	end

	def post_car_name
		@search_results_posts = CocheDato.suggestSearchCarName(params["carName"])
		respond_to do |format|
			format.js { render layout: false }
		end
	end

	def yesCar_noOrigin_noYear_noMpg_noHorsepower
		@search_results_posts = CocheDato.suggestSearchCarName(params["carName"])
		respond_to do |format|
			format.js { render layout: false }
		end
	end

  # GET /statics or /statics.json
  def index
    # @statics = Static.all
  end

  # GET /statics/1 or /statics/1.json
  def show
  end

  # GET /statics/new
  def new
    @static = Static.new
  end

  # GET /statics/1/edit
  def edit
  end

  # POST /statics or /statics.json
  def create
    @static = Static.new(static_params)

    respond_to do |format|
      if @static.save
        format.html { redirect_to static_url(@static), notice: "Static was successfully created." }
        format.json { render :show, status: :created, location: @static }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @static.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /statics/1 or /statics/1.json
  def update
    respond_to do |format|
      if @static.update(static_params)
        format.html { redirect_to static_url(@static), notice: "Static was successfully updated." }
        format.json { render :show, status: :ok, location: @static }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @static.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /statics/1 or /statics/1.json
  def destroy
    @static.destroy

    respond_to do |format|
      format.html { redirect_to statics_url, notice: "Static was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_static
      @static = Static.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def static_params
      params.fetch(:static, {})
    end
end

app/helpers/statics_helper.rb
module StaticsHelper
end

app/views/statics/_form.html.erb
<%= form_with(model: static) do |form| %>
  <% if static.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(static.errors.count, "error") %> prohibited this static from being saved:</h2>

      <ul>
        <% static.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/statics/_hide_data.html.erb
<h1> Okay!</h1>

app/views/statics/_retrieve_searches.html.erb
<table>
	<thead>
		<tr>
			<th>The Name</th>
		</tr>
	</thead>

	<tbody>
		 <% @search_results_posts.each_with_index do |coche, index| %>
			<tr>
				<td><%= index + 1 %>.</td>
				<td><%= coche.car %></td>
				<td><%= coche.origin %></td>
			</tr>
		 <% end %>
	</tbody>
</table>

app/views/statics/edit.html.erb
<h1>Editing Static</h1>

<%= render 'form', static: @static %>

<%= link_to 'Show', @static %> |
<%= link_to 'Back', statics_path %>

app/views/statics/execute_search.js.erb
$("#current_coches").html("<%= escape_javascript(render partial: 'statics/execute_search') %>");

app/views/statics/get_data.js.erb
$("#current_customer").html("<%= escape_javascript(render partial: 'statics/get_data', locals: { test_data: @test_data } ) %>");

app/views/statics/home.html.erb
<h1> Home </h1>

<p>Search for your dream car.</p>

app/views/statics/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Statics</h1>

<%= text_field_tag :search, "", class:"search_companies" %>

<tbody class="company_tbody_content">
	<%= render "index_content" %>
</tbody>

<!--table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    % @statics.each do |static| %>
      <tr>
        <td>%= link_to 'Show', static %></td>
        <td>%= link_to 'Edit', edit_static_path(static) %></td>
        <td>%= link_to 'Destroy', static, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    % end %>
  </tbody>
</table>

<br>

<!--= link_to 'New Static', new_static_path %>


	<h4>Search by Car Name:</h4>
	<= form_tag(static_index_path, method: :get) do %>
		%= text_field_tag(:search, params[:search]) %>
		%= submit_tag("Search") %>
	% end %-->

app/views/statics/new.html.erb
<h1>New Static</h1>

<%= render 'form', static: @static %>

<%= link_to 'Back', statics_path %>

app/views/statics/post_car_name.js.erb
$("#blogpost-table-two").hide();
$("#current_retrieve").html("<%= escape_javascript(render partial: 'statics/post_car_name') %>");

app/views/statics/renovated_search.html.erb
<h1> Renovated Search </h1>

<div class="row">
	<div class="col-6">
		<div style="width: 700px;" class="border rounded bg-light">
			
			<div class="container" style="padding-top: 25px; padding-bottom: 60px;">
				Search by car name:<br>
				<input type="text" id="car_name_val" name="car_name_val" class="form-control" value=""><br>

				Origin:<br>
				<input type="text" id="country_origin" name="country_origin" class="form-control" value=""><br>

				Year:<br>
				<input type="text" id="year_val" name="year_val" class="form-control" value=""><br>

				<input type="checkbox" id="mpg_val" name="mpg_val" class="form-control" value="">
				Search by MPG?

				<input type="checkbox" id="horsepower_val" name="horsepower_val" class="form-control" value="">
				Search by horsepower?
			</div>

		</div>
	</div>
</div>
	
<div id="current_retrieve"></div>

<!--div id="blogpost-table-two">
  <table>
    <thead>
      <tr>
        <th>The Name</th>
      </tr>
    </thead>

    <tbody>
       < @rhs_coches.each_with_index do |coche, index| %>
        <tr>
          <td><= index + 1 %>.</td>
          <td><= coche.car %></td>
          <td><= coche.origin %></td>
        </tr>
       < end %>
    </tbody>
  </table>
</div-->

<!--%= text_field_tag 'renovated_search', '', remote: true %-->

<!--%= form_tag(retrieve_searches_coche_datos_path, method: "get", remote: true, html: {id: 'edit-form'}) do %>
    Search by car name:<br>
    <= text_field_tag 'renovated_search', '', remote: true %--> <!--, onkeyup: "$(this).parent('form').submit();" %-->
		<!--%= submit_tag 'Search', class: "btn btn-dark search-btn" %>
< end %-->

app/views/statics/retrieve_searches.js.erb
if(<%= @search_results_posts.size %> > 0) {
	$("#blogpost-table-two").hide();
	$("#current_retrieve").html("<%= escape_javascript(render partial: 'statics/retrieve_searches', locals: { search_results_posts: @search_results_posts }) %>");
} else {
	$("#blogpost-table-two").show();
	$("#current_retrieve").hide();
}

app/views/statics/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_static_path(@static) %> |
<%= link_to 'Back', statics_path %>

app/views/statics/test.html.erb
<h1> Test </h1>

<%= link_to 'Get Data', get_data_statics_path, remote: true %>
<%= link_to 'Hide Data', hide_data_statics_path, remote: true %>

<div id="current_customer"></div>