config/routes.rb
Rails.application.routes.draw do
  resources :coche_datos do
		collection do
			get :search
			get :ajax_search
			get :retrieve_searches
			get :buscar_autocomplete
			get :index_latest_autocomplete
			get :buscar_latest_autocomplete # fetches JSON data via GET request

			get :search_all_cars
			post :noCar_noOrigin_noYear_noMpg_noHorsepower 
			post :yesCar_noOrigin_noYear_noMpg_noHorsepower 
			post :noCar_noOrigin_noYear_noMpg_yesHorsepower
			post :noCar_noOrigin_noYear_yesMpg_noHorsepower
			post :noCar_noOrigin_noYear_yesMpg_yesHorsepower
			post :noCar_noOrigin_yesYear_noMpg_noHorsepower
			post :noCar_noOrigin_yesYear_noMpg_yesHorsepower
			post :noCar_noOrigin_yesYear_yesMpg_noHorsepower

			post :noCar_noOrigin_yesYear_yesMpg_yesHorsepower
			post :noCar_yesOrigin_noYear_noMpg_noHorsepower
			post :noCar_yesOrigin_noYear_noMpg_yesHorsepower
			post :noCar_yesOrigin_noYear_yesMpg_noHorsepower
			post :noCar_yesOrigin_noYear_yesMpg_yesHorsepower
			post :noCar_yesOrigin_yesYear_noMpg_noHorsepower
			post :noCar_yesOrigin_yesYear_noMpg_yesHorsepower
			post :noCar_yesOrigin_yesYear_yesMpg_noHorsepower
			post :noCar_yesOrigin_yesYear_yesMpg_yesHorsepower
			# post :yesCar_noOrigin_noYear_noMpg_noHorsepower
			post :yesCar_noOrigin_noYear_noMpg_yesHorsepower
			post :yesCar_noOrigin_noYear_yesMpg_noHorsepower
			post :yesCar_noOrigin_noYear_yesMpg_yesHorsepower
			post :yesCar_noOrigin_yesYear_noMpg_noHorsepower
			post :yesCar_noOrigin_yesYear_noMpg_yesHorsepower
			post :yesCar_noOrigin_yesYear_yesMpg_noHorsepower
			post :yesCar_noOrigin_yesYear_yesMpg_yesHorsepower
			post :yesCar_yesOrigin_noYear_noMpg_noHorsepower
			post :yesCar_yesOrigin_noYear_noMpg_yesHorsepower
			post :yesCar_yesOrigin_noYear_yesMpg_noHorsepower
			post :yesCar_yesOrigin_noYear_yesMpg_yesHorsepower
			post :yesCar_yesOrigin_yesYear_noMpg_noHorsepower
			post :yesCar_yesOrigin_yesYear_noMpg_yesHorsepower
			post :yesCar_yesOrigin_yesYear_yesMpg_noHorsepower
			post :yesCar_yesOrigin_yesYear_yesMpg_yesHorsepower
		end
	end

	# root 'coche_datos#index'
	# root 'statics#home'
	root 'coche_datos#index_autocomplete'
	# get 'coche_datos/buscar_autocomplete', to: 'coche_datos#buscar_autocomplete'

  resources :statics do
		collection do
			get :test
			get :get_data
			get :hide_data
			get :renovated_search
			post :retrieve_searches
			post :post_car_name
		end
	end

	post 'statics/execute_search', to: 'statics#execute_search'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
	# root 'statics#index'
end

app/controllers/coche_datos_controller.rb
class CocheDatosController < ApplicationController
  # before_action :set_coche_dato, only: %i[ show edit update destroy ]
	# before_action :force_json, only: [:buscar_autocomplete, :buscar_latest_autocomplete]
	before_action :force_json, only: [:buscar_autocomplete, :buscar_latest_autocomplete]

	def search_all_cars
		puts "==========================="
		puts MultiJson.dump(CocheDato.mapping.to_hash, pretty: true)
		puts "==========================="
	end

	def noCar_noOrigin_noYear_noMpg_noHorsepower ###
    @matches = CocheDato.all
		respond_to do |format|
			format.js { render template: "coche_datos/display_car_data", layout: false}
		end
	end

	def yesCar_noOrigin_noYear_noMpg_noHorsepower ###
    @matches = CocheDato.yesCar_noOrigin_noYear_noMpg_noHorsepower(params["carName"])
		respond_to do |format|
			format.js { render template: "coche_datos/display_car_data", layout: false}
		end
	end

	def noCar_noOrigin_noYear_noMpg_yesHorsepower ###
    @matches = CocheDato.noCar_noOrigin_noYear_noMpg_yesHorsepower(params["horsepowerLower"], params["horsepowerHigher"])
		respond_to do |format|
			format.js { render template: "coche_datos/display_car_data", layout: false}
		end
	end

	# FIXED 
	def noCar_noOrigin_noYear_yesMpg_noHorsepower ###
		if(params.key?("mpgLower"))
			@matches = CocheDato.noCar_noOrigin_noYear_yesMpg_noHorsepower(params["mpgLower"], params["mpgHigher"], nil)
		end
		if(params.key?("mpgExact"))
			@matches = CocheDato.noCar_noOrigin_noYear_yesMpg_noHorsepower(nil, nil, params["mpgExact"])
		end
		respond_to do |format|
			format.js { render template: "coche_datos/display_car_data", layout: false}
		end
	end

	# FIXED
	def noCar_noOrigin_noYear_yesMpg_yesHorsepower ###
		# @matches = CocheDato.noCar_noOrigin_noYear_yesMpg_yesHorsepower(params["mpgLower"], params["mpgHigher"], params["horsepowerLower"], params["horsepowerHigher"])
		if(params.key?("mpgLower") && params.key?("horsepowerLower"))
			@matches = CocheDato.noCar_noOrigin_noYear_yesMpg_yesHorsepower(params["mpgLower"], params["mpgHigher"], nil, params["horsepowerLower"], params["horsepowerHigher"], nil)
		elsif(params.key?("mpgLower") && params.key?("horsepowerExact"))
			@matches = CocheDato.noCar_noOrigin_noYear_yesMpg_yesHorsepower(params["mpgLower"], params["mpgHigher"], nil, nil, nil, params["horsepowerExact"])
		elsif(params.key?("mpgExact") && params.key?("horsepowerLower"))
			@matches = CocheDato.noCar_noOrigin_noYear_yesMpg_yesHorsepower(nil, nil, params["mpgExact"], params["horsepowerLower"], params["horsepowerHigher"], nil)
		elsif(params.key?("mpgExact") && params.key?("horsepowerExact"))
			@matches = CocheDato.noCar_noOrigin_noYear_yesMpg_yesHorsepower(nil, nil, params["mpgExact"], nil, nil, params["horsepowerExact"])
		end
		respond_to do |format|
			format.js { render template: "coche_datos/display_car_data", layout: false}
		end
	end

	def noCar_noOrigin_yesYear_noMpg_noHorsepower ###
		@matches = CocheDato.noCar_noOrigin_yesYear_noMpg_noHorsepower(params["yearVal"])
		respond_to do |format|
			format.js { render template: "coche_datos/display_car_data", layout: false}
		end
	end

	def noCar_noOrigin_yesYear_noMpg_yesHorsepower ###
		@matches = CocheDato.noCar_noOrigin_yesYear_noMpg_yesHorsepower(params["yearVal"], params["horsepowerLower"], params["horsepowerHigher"])
		respond_to do |format|
			format.js { render template: "coche_datos/display_car_data", layout: false}
		end
	end

	# FIXED
	def noCar_noOrigin_yesYear_yesMpg_noHorsepower ###
		if(params.key?("mpgLower"))
			@matches = CocheDato.noCar_noOrigin_yesYear_yesMpg_noHorsepower(params["yearVal"], params["mpgLower"], params["mpgHigher"], nil)
		end
		if(params.key?("mpgExact"))
			@matches = CocheDato.noCar_noOrigin_yesYear_yesMpg_noHorsepower(params["yearVal"], nil, nil, params["mpgExact"])
		end
		respond_to do |format|
			format.js { render template: "coche_datos/display_car_data", layout: false}
		end
	end

	# FIXED
	def noCar_noOrigin_yesYear_yesMpg_yesHorsepower
		# @matches = CocheDato.noCar_noOrigin_yesYear_yesMpg_yesHorsepower(params["yearVal"], params["mpgLower"], params["mpgHigher"], params["horsepowerLower"], params["horsepowerHigher"])
		if(params.key?("mpgLower") && params.key?("horsepowerLower"))
			@matches = CocheDato.noCar_noOrigin_yesYear_yesMpg_yesHorsepower(params["yearVal"], params["mpgLower"], params["mpgHigher"], nil, params["horsepowerLower"], params["horsepowerHigher"], nil)
		elsif(params.key?("mpgLower") && params.key?("horsepowerExact"))
			@matches = CocheDato.noCar_noOrigin_yesYear_yesMpg_yesHorsepower(params["yearVal"], params["mpgLower"], params["mpgHigher"], nil, nil, nil, params["horsepowerExact"])
		elsif(params.key?("mpgExact") && params.key?("horsepowerLower"))
			@matches = CocheDato.noCar_noOrigin_yesYear_yesMpg_yesHorsepower(params["yearVal"], nil, nil, params["mpgExact"], params["horsepowerLower"], params["horsepowerHigher"], nil)
		elsif(params.key?("mpgExact") && params.key?("horsepowerExact"))
			@matches = CocheDato.noCar_noOrigin_yesYear_yesMpg_yesHorsepower(params["yearVal"], nil, nil, params["mpgExact"], nil, nil, params["horsepowerExact"])
		end
		respond_to do |format|
			format.js { render template: "coche_datos/display_car_data", layout: false }
		end
	end

	def noCar_yesOrigin_noYear_noMpg_noHorsepower ###
		@matches = CocheDato.noCar_yesOrigin_noYear_noMpg_noHorsepower(params["originName"])
		respond_to do |format|
			format.js { render template: "coche_datos/display_car_data", layout: false}
		end
	end

	def noCar_yesOrigin_noYear_noMpg_yesHorsepower ###
		@matches = CocheDato.noCar_yesOrigin_noYear_noMpg_yesHorsepower(params["originName"], params["horsepowerLower"], params["horsepowerHigher"])
		respond_to do |format|
			format.js { render template: "coche_datos/display_car_data", layout: false }
		end
	end

	# FIXED
	def noCar_yesOrigin_noYear_yesMpg_noHorsepower
		if(params.key?("mpgLower"))
			@matches = CocheDato.noCar_yesOrigin_noYear_yesMpg_noHorsepower(params["originName"], params["mpgLower"], params["mpgHigher"], nil)
		end
		if(params.key?("mpgExact"))
			@matches = CocheDato.noCar_yesOrigin_noYear_yesMpg_noHorsepower(params["originName"], nil, nil, params["mpgExact"])
		end
		respond_to do |format|
			format.js { render template: "coche_datos/display_car_data", layout: false }
		end
	end

	# fix
	def noCar_yesOrigin_noYear_yesMpg_yesHorsepower
		@matches = CocheDato.noCar_yesOrigin_noYear_yesMpg_yesHorsepower(params["originName"], params["mpgLower"], params["mpgHigher"], params["horsepowerLower"], params["horsepowerHigher"])
		if(params.key?("mpgLower") && params.key?("horsepowerLower"))
		end
		if(params.key?("mpgLower") && params.key?("horsepowerExact"))
		end
		if(params.key?("mpgExact") && params.key?("horsepowerLower"))
		end
		if(params.key?("mpgExact") && params.key?("horsepowerExact"))
		end
		respond_to do |format|
			format.js { render template: "coche_datos/display_car_data", layout: false }
		end
	end

	def noCar_yesOrigin_yesYear_noMpg_noHorsepower ###
		@matches = CocheDato.noCar_yesOrigin_yesYear_noMpg_noHorsepower(params["originName"], params["yearVal"])
		respond_to do |format|
			format.js { render template: "coche_datos/display_car_data", layout: false}
		end
	end

	# FIXED
	def noCar_yesOrigin_yesYear_yesMpg_noHorsepower
		if(params.key?("mpgLower"))
			@matches = CocheDato.noCar_yesOrigin_yesYear_yesMpg_noHorsepower(params["originName"], params["yearVal"], params["mpgLower"], params["mpgHigher"], nil)
		end
		if(params.key?("mpgExact"))
			@matches = CocheDato.noCar_yesOrigin_yesYear_yesMpg_noHorsepower(params["originName"], params["yearVal"], nil, nil, params["mpgExact"])
		end
		respond_to do |format|
			format.js { render template: "coche_datos/display_car_data", layout: false}
		end
	end

	# fix
	def noCar_yesOrigin_yesYear_yesMpg_yesHorsepower
		@matches = CocheDato.noCar_yesOrigin_yesYear_yesMpg_yesHorsepower(params["originName"], params["yearVal"], params["mpgLower"], params["mpgHigher"], params["horsepowerLower"], params["horsepowerHigher"])
		if(params.key?("mpgLower") && params.key?("horsepowerLower"))
		end
		if(params.key?("mpgLower") && params.key?("horsepowerExact"))
		end
		if(params.key?("mpgExact") && params.key?("horsepowerLower"))
		end
		if(params.key?("mpgExact") && params.key?("horsepowerExact"))
		end
		respond_to do |format|
			format.js { render template: "coche_datos/display_car_data", layout: false}
		end
	end

	def yesCar_noOrigin_noYear_noMpg_yesHorsepower 
		@matches = CocheDato.yesCar_noOrigin_noYear_noMpg_yesHorsepower(params["carName"], params["horsepowerLower"], params["horsepowerHigher"])
		respond_to do |format|
			format.js { render template: "coche_datos/display_car_data", layout: false}
		end
	end

	# fix
	def yesCar_noOrigin_noYear_yesMpg_noHorsepower
		@matches = CocheDato.yesCar_noOrigin_noYear_yesMpg_noHorsepower(params["carName"], params["mpgLower"], params["mpgHigher"])
		respond_to do |format|
			format.js { render template: "coche_datos/display_car_data", layout: false}
		end
	end

	# fix
	def yesCar_noOrigin_noYear_yesMpg_yesHorsepower
		if(params.key?("mpgLower") && params.key?("horsepowerLower"))
		end
		if(params.key?("mpgLower") && params.key?("horsepowerExact"))
		end
		if(params.key?("mpgExact") && params.key?("horsepowerLower"))
		end
		if(params.key?("mpgExact") && params.key?("horsepowerExact"))
		end
		@matches = CocheDato.yesCar_noOrigin_noYear_yesMpg_yesHorsepower(params["carName"], params["mpgLower"], params["mpgHigher"], params["horsepowerLower"], params["horsepowerHigher"])
		respond_to do |format|
			format.js { render template: "coche_datos/display_car_data", layout: false}
		end
	end

	def yesCar_noOrigin_yesYear_noMpg_noHorsepower ### 
		@matches = CocheDato.yesCar_noOrigin_yesYear_noMpg_noHorsepower(params["carName"], params["yearVal"])
		respond_to do |format|
			format.js { render template: "coche_datos/display_car_data", layout: false}
		end
	end

	def yesCar_noOrigin_yesYear_noMpg_yesHorsepower

app/helpers/coche_datos_helper.rb
module CocheDatosHelper
end

app/views/coche_datos/_ajax_search.js.erb
$("#blogpost-table").hide();
$("#search-results").html("<%= escape_javascript(render :partial => 'results') %>");
// $("#search-results").append("<= escape_javascript(render :partial => 'results') %>");

app/views/coche_datos/_buscar_latest_autocomplete.html.erb
<table>
	<thead>
		<tr>
			<th>Name</th>
		</tr>
	</thead>

	<tbody>
		 <% @people.each do |coche| %>
			<tr>
				<td><%= coche.car %></td>
			</tr>
		 <% end %>
	</tbody>
</table>

app/views/coche_datos/_form.html.erb
<%= form_with(model: coche_dato) do |form| %>
  <% if coche_dato.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(coche_dato.errors.count, "error") %> prohibited this coche_dato from being saved:</h2>

      <ul>
        <% coche_dato.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/coche_datos/_index_content.html.erb
<h1> index content </h1>

app/views/coche_datos/_noCar_noOrigin_yesYear_noMpg_noHorsepower.html.erb
<div>
  <table>
    <thead>
      <tr>
        <th>#</th>
        <th>Car</th>
        <th>Model</th>
        <th>MPG</th>
        <th>Cylinders</th>
        <th>Horsepower</th>
        <th>Weight</th>
        <th>Origin</th>
      </tr>
    </thead>

    <tbody>
       <% @matches.each_with_index do |coche, index| %>
        <tr>
          <td><%= index + 1 %>.</td>
          <td><%= coche.car %></td>
          <td><%= coche.model %></td>
          <td><%= coche.mpg %></td>
          <td><%= coche.cylinders %></td>
          <td><%= coche.horsepower %></td>
          <td><%= coche.weight %></td>
          <td><%= coche.origin %></td>
        </tr>
       <% end %>
    </tbody>
  </table>
</div>

app/views/coche_datos/_person.html.erb
<h4><%= person.car %></h4>

app/views/coche_datos/_results.html.erb
Total size: <%= @search_results_posts.count %>

<table>
	<thead>
		<tr>
			<th>Coche Name</th>
		</tr>
	</thead>

	<tbody>
		<% @search_results_posts.each do |coche| %>
			<tr>
				<td><%= coche.car %></td>
			</tr>
		<% end %>
	</tbody>
</table>

app/views/coche_datos/ajax_search.html.erb
<h1>Ajax Search</h1>

<!-- to submit a form via AJAX in Rails, add remote: true to the form_tag argument -->

<div style="width: 700px;" class="border rounded bg-light">
	<%= form_tag(retrieve_searches_coche_datos_path, method: "get", remote: true) do %>
		Search by car name:<br>
		<%= text_field_tag :search, params[:search], placeholder: "Enter search term" %><br><br>

		<%= submit_tag 'Search', class: "btn btn-dark search-btn" %>
	<% end %>
</div>
<br><br>

<div id="blogpost-table">
	<table>
		<thead>
			<tr>
				<th>The Name</th>
			</tr>
		</thead>

		<tbody>
			 <% @rhs_coches.each do |coche| %>
				<tr>
					<td><%= coche.car %></td>
				</tr>
			 <% end %>
		</tbody>
	</table>
</div>

<div id="search-results">
</div>

app/views/coche_datos/edit.html.erb
<h1>Editing Coche Dato</h1>

<%= render 'form', coche_dato: @coche_dato %>

<%= link_to 'Show', @coche_dato %> |
<%= link_to 'Back', coche_datos_path %>

app/views/coche_datos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>INDEX Coche Datos</h1>

<p>
  Press <%= link_to 'here', search_coche_datos_path %> to search for coche datos.
</p>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @coche_datos.each do |coche| %>
      <tr>
				<td><%= coche.car %></td>
				<td><%= coche.mpg %></td>
				<td><%= coche.cylinders %></td>
				<td><%= coche.displacement %></td>
				<td><%= coche.horsepower %></td>
				<td><%= coche.weight %></td>
				<td><%= coche.acceleration %></td>
				<td><%= coche.model %></td>
				<td><%= coche.origin %></td>
        <td><%= link_to 'Show', coche %></td>
        <td><%= link_to 'Edit', edit_coche_dato_path(coche) %></td>
        <td><%= link_to 'Destroy', coche, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Coche Dato', new_coche_dato_path %>

app/views/coche_datos/index_latest_autocomplete.html.erb
<h1>Index Latest Autocomplete</h1>

<input id="inputOne" type="search" placeholder="Enter car name..." data-behavior="autocomplete">

<br><br><br><br><br><br><br><br><br><br><br>

<input id="inputTwo" placeholder="Other car">

<!--div style="width: 700px;" class="border rounded bg-light">
	<= form_tag(buscar_latest_autocomplete_coche_datos_path, method: "get", remote: true) do %>
		Search by car name:<br>
		<= text_field_tag :search, params[:search], placeholder: "Enter search term" %><br><br>

		<= submit_tag 'Search', class: "btn btn-dark search-btn" %>
	< end %>
</div-->

<div id="search-results-two">
</div>

<div id="search-results-three">
</div>

<%= render partial: 'coche_datos/car_data' %>

app/views/coche_datos/search.html.erb
<style>
	.search-btn {
		float: right;
	}
</style>
<script>
function onClick() {
	var mpgDiv = document.getElementById('mpg_fields');
	var mpgPlaceholderDiv = document.getElementById('mpg_tmp_placeholder');
	if(mpgDiv.style.display == 'none') {
		mpgDiv.style.display = 'block';
		mpgPlaceholderDiv = 'none';
	} else {
		mpgDiv.style.display = 'none';
		mpgPlaceholderDiv = 'block';
	}
}

function onClickTwo() {
	var horsepwerDiv = document.getElementById('horsepower_fields');
	if(horsepwerDiv.style.display == 'none') {
		horsepwerDiv.style.display = 'block';
	} else {
		horsepwerDiv.style.display = 'none';
	}
}

function hideFields() {
	var mpgDiv = document.getElementById('mpg_fields');
	mpgDiv.style.display = 'none';
	var horsepowerDiv = document.getElementById('horsepower_fields');
	horsepowerDiv.style.display = 'none';
}

window.onload = hideFields();

</script>

<h1>Search for 70's and 80's Cars</h1>

<div class="row">
	<div class="col-6">
		<div style="width: 700px;" class="border rounded bg-light">

			<div class="container" style="padding-top: 25px; padding-bottom: 60px;">
				<%= form_for :search_coche_datos, url: search_coche_datos_path, method: :get do |form| %>
					Search by car name:<br>
					<%= form.text_field :query, value: params[:search_coche_datos].presence && params[:search_coche_datos][:query], class: "form-control" %><br>

					Origin: <%= form.text_field :country_origin, value: params[:search_coche_datos].presence && params[:search_coche_datos][:country_origin], class: "form-control" %><br>
					Year: <%= form.number_field :model, min: 50, max: 99, :step => 'any', class: "number form-control ", placeholder: "0" %><br>

					<div class="row">
						<div class="col-6">
							<%= form.check_box :MPG_checkbox, class: "form-check-input", onclick: "onClick();" %>&nbsp;Search by MPG?<br>
						</div>
						<div class="col-6">
							<%= form.check_box :horsepower_checkbox, class: "form-check-input", onclick: "onClickTwo();" %>&nbsp;Search by horsepower?<br>
						</div>
					</div>

					<div class="row">
						<div class="col-6">
							<div id="mpg_fields">
								MPG: <%= form.number_field :MPG, min: 1, max: 200, :step => 'any', class: "form-control number", placeholder: "0" %><br>
								MPG Two: <%= form.number_field :MPG_two, min: 1, max: 200, :step => 'any', class: "form-control number", placeholder: "0" %><br>
							</div>
						</div>

						<div class="col-6" id="horsepower_fields">
							<!--%= form.check_box :horsepower_checkbox, class: "form-check-input" %>&nbsp;Search by horsepower?<br-->
							Horsepower: <%= form.number_field :horsepower, min: 50, max: 500, :step => 'any', class: "number form-control", placeholder: "0" %><br>
							Horsepower Two: <%= form.number_field :horsepower_two, min: 50, max: 500, :step => 'any', class: "number form-control", placeholder: "0" %><br>
						</div>
					</div>
				
					<%= form.submit 'Search', class: "btn btn-dark search-btn" %>
				<% end %>
			</div>

		</div>
	</div>

	<div class="col-6">
		<h1>Coches</h1>

		<table>
      <thead>
         <tr>
           <th>Car</th>
           <th>MPG</th>
           <th>Cylinders</th>
           <!--th>Displacement</th-->
           <th>Horsepower</th>
           <th>Weight</th>
           <!--th>Acceleration</th-->
           <th>Model</th>
           <th>Origin</th>
         </tr>
			</thead>

			<tbody>
				<% @rhs_coches.each do |coche| %>
					<tr>
						<td><%= coche.car %></td>
						<td><%= coche.mpg %></td>
						<td><%= coche.cylinders %></td>
						<!--td>%= coche.displacement %></td-->
						<td><%= coche.horsepower %></td>
						<td><%= coche.weight %></td>
						<!--td><= coche.acceleration %></td-->
						<td><%= coche.model %></td>
						<td><%= coche.origin %></td>
					</tr>
				<% end %>
			</tbody>
		</table>

	</div>
</div>


<% if @coche_datos.nil? %>
    <h2>No coches found matching your query.</h2>
<% else %>
    <h2>Search results</h2>
		<p>Count: <%= @coche_datos.size %></p>
<% end %>


<!--% if @coche_datos.nil? %>
	<h1><b>Car Datum is null</b></h1>

 else %>

	<h1>Car Datum is not null</h1>
    <table style="width: 100%;">
      <thead>
         <tr>
           <th>#</th>
           <th>Car</th>
           <th>MPG</th>
           <th>Cylinders</th>
           <th>Displacement</th>
           <th>Horsepower</th>
           <th>Weight</th>
           <th>Acceleration</th>
           <th>Model</th>
           <th>Origin</th>
         </tr>
      <!--/thead-->

		<!--tbody>
			 @coche_datos.each_with_index do |coche, index| %>
				<tr>
					<td><= (index + 1) %></td>
					<td><= coche.car %></td>
					<td><= coche.mpg %></td>
					<td><= coche.cylinders %></td>
					<td><= coche.displacement %></td>
					<td><= coche.horsepower %></td>
					<td><= coche.weight %></td>
					<td><= coche.acceleration %></td>
					<td><= coche.model %></td>
					<td><= coche.origin %></td>
					<td><= link_to 'View', coche_dato_path(coche.id) %></td>
				</tr>
			< end %>
			<tbody>
		</table-->

<!--% end %-->

app/views/coche_datos/show.html.erb
<!--p id="notice"><= notice %></p>

<= link_to 'Edit', edit_coche_dato_path(@coche_dato) %> |
<= link_to 'Back', coche_datos_path %-->