config/routes.rb
Rails.application.routes.draw do
  resources :coche_datos do
		collection do
			get :search
			get :ajax_search
			get :retrieve_searches
			get :buscar_autocomplete
			get :index_latest_autocomplete
			get :buscar_latest_autocomplete # fetches JSON data via GET request

			get :search_all_cars
			post :noCar_noOrigin_noYear_noMpg_noHorsepower 
			post :yesCar_noOrigin_noYear_noMpg_noHorsepower 
			post :noCar_noOrigin_noYear_noMpg_yesHorsepower
			post :noCar_noOrigin_noYear_yesMpg_noHorsepower
			post :noCar_noOrigin_noYear_yesMpg_yesHorsepower
			post :noCar_noOrigin_yesYear_noMpg_noHorsepower
			post :noCar_noOrigin_yesYear_noMpg_yesHorsepower
			post :noCar_noOrigin_yesYear_yesMpg_noHorsepower

			post :noCar_noOrigin_yesYear_yesMpg_yesHorsepower
			post :noCar_yesOrigin_noYear_noMpg_noHorsepower
			post :noCar_yesOrigin_noYear_noMpg_yesHorsepower
			post :noCar_yesOrigin_noYear_yesMpg_noHorsepower
			post :noCar_yesOrigin_noYear_yesMpg_yesHorsepower
			post :noCar_yesOrigin_yesYear_noMpg_noHorsepower
			post :noCar_yesOrigin_yesYear_noMpg_yesHorsepower
			post :noCar_yesOrigin_yesYear_yesMpg_noHorsepower
			post :noCar_yesOrigin_yesYear_yesMpg_yesHorsepower
			# post :yesCar_noOrigin_noYear_noMpg_noHorsepower
			post :yesCar_noOrigin_noYear_noMpg_yesHorsepower
			post :yesCar_noOrigin_noYear_yesMpg_noHorsepower
			post :yesCar_noOrigin_noYear_yesMpg_yesHorsepower
			post :yesCar_noOrigin_yesYear_noMpg_noHorsepower
			post :yesCar_noOrigin_yesYear_noMpg_yesHorsepower
			post :yesCar_noOrigin_yesYear_yesMpg_noHorsepower
			post :yesCar_noOrigin_yesYear_yesMpg_yesHorsepower
			post :yesCar_yesOrigin_noYear_noMpg_noHorsepower
			post :yesCar_yesOrigin_noYear_noMpg_yesHorsepower
			post :yesCar_yesOrigin_noYear_yesMpg_noHorsepower
			post :yesCar_yesOrigin_noYear_yesMpg_yesHorsepower
			post :yesCar_yesOrigin_yesYear_noMpg_noHorsepower
			post :yesCar_yesOrigin_yesYear_noMpg_yesHorsepower
			post :yesCar_yesOrigin_yesYear_yesMpg_noHorsepower
			post :yesCar_yesOrigin_yesYear_yesMpg_yesHorsepower
		end
	end

	# root 'coche_datos#index'
	# root 'statics#home'
	root 'coche_datos#index_autocomplete'
	# get 'coche_datos/buscar_autocomplete', to: 'coche_datos#buscar_autocomplete'

  resources :statics do
		collection do
			get :test
			get :get_data
			get :hide_data
			get :renovated_search
			post :retrieve_searches
			post :post_car_name
		end
	end

	post 'statics/execute_search', to: 'statics#execute_search'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
	# root 'statics#index'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Car Search</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

	<!--nav class="navbar navbar-expand-lg bg-light navbar-light pl-4" style="display: flex; justify-content: space-between;"-->
	<nav class="navbar navbar-expand-lg bg-light navbar-light" style="padding-left: 125px;">
		<div class="container-fluid">
			<ul class="navbar-nav">
				<li class="nav-item">
					<%= link_to "Home", root_path, class: 'nav-link' %>
				</li>
			 <li class="nav-item">
					<%= link_to "Search", search_coche_datos_path, class: 'nav-link' %>
				</li>
			 <li class="nav-item">
					<%= link_to "Search All Cars", search_all_cars_coche_datos_path, class: 'nav-link' %>
				</li>
			 <li class="nav-item">
					<%= link_to "Ajax Search", ajax_search_coche_datos_path, class: 'nav-link' %>
				</li>
			 <li class="nav-item">
					<%= link_to "Index Latest Search", index_latest_autocomplete_coche_datos_path, class: 'nav-link' %>
				</li>
			 <li class="nav-item">
					<%= link_to "Test Page", test_statics_path, class: 'nav-link' %>
				</li>
			 <li class="nav-item">
					<%= link_to "Renovated Search", renovated_search_statics_path, class: 'nav-link' %>
				</li>
			</ul>
		</div>
	</nav>

  <main>
    <%= yield %>
  </main>

	<div class="footer">
		<center><h3 style="color: white;">Happy searching!</h3></center>
	</div>
</html>